### ISSUE TITLE
if i clean cookies in chrome evercookie forget me

### ISSUE THREAD

**Issue by sveinjoe** [samyk/evercookie#81] opened 2014-11-05 08:30 UTC
if i clean cookies in chrome evercookie forget me

1.visite http://samy.pl/evercookie/ and click to create an evercookie;
2.clean cookies in chrome;
3.close chrome;
4.restart chrome;
5.visite http://samy.pl/evercookie/ and click to rediscover evercookie;
6.evercookie has forgot me.

my english is so poor, don't laugth at me :dancers: 

![1](https://cloud.githubusercontent.com/assets/8053947/4914671/e1634a74-64c5-11e4-88e3-29710746c052.png)
![2](https://cloud.githubusercontent.com/assets/8053947/4914674/ea30d162-64c5-11e4-891f-16ca9e740f25.png)
![3](https://cloud.githubusercontent.com/assets/8053947/4914679/ef670c50-64c5-11e4-83fc-a441dd7a1e68.png)

**Comment by samyk** [comment] 2015-03-14 03:13
Closing this as it's not a bug, Chrome simply now properly handles cleaning evercookie's existing methods!

**Closed by samyk** 2015-03-14 03:13 UTC
